apiVersion: v1
kind: Template
metadata:
  name: observatorium-traces
objects:
- apiVersion: jaegertracing.io/v1
  kind: Jaeger
  metadata:
    labels:
      app.kubernetes.io/component: rhobs
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: otelcol
      app.kubernetes.io/part-of: observatorium
    name: observatorium-jaeger-rhobs
  spec:
    strategy: allinone
- apiVersion: jaegertracing.io/v1
  kind: Jaeger
  metadata:
    labels:
      app.kubernetes.io/component: telemeter
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: otelcol
      app.kubernetes.io/part-of: observatorium
    name: observatorium-jaeger-telemeter
  spec:
    strategy: allinone
- apiVersion: opentelemetry.io/v1alpha1
  kind: OpenTelemetryCollector
  metadata:
    labels:
      app.kubernetes.io/component: jaeger
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: otelcol
      app.kubernetes.io/part-of: observatorium
    name: observatorium-otel
  spec:
    config: |-
      exporters:
        jaeger/rhobs:
          endpoint: "observatorium-jaeger-rhobs-collector:14250"
          tls:
            insecure: true
        jaeger/telemeter:
          endpoint: "observatorium-jaeger-telemeter-collector:14250"
          tls:
            insecure: true
      processors:
        routing:
          from_attribute: "X-Tenant"
          table:
          - exporters:
            - "jaeger/rhobs"
            value: "rhobs"
          - exporters:
            - "jaeger/telemeter"
            value: "telemeter"
      receivers:
        otlp:
          protocols:
            grpc: {}
      service:
        pipelines:
          traces:
            exporters:
            - "jaeger/rhobs"
            - "jaeger/telemeter"
            processors:
            - "routing"
            receivers:
            - "otlp"
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.46.0
    mode: deployment
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: rhobs-opentelemetry
    namespace: openshift-operators
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: opentelemetry-product
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: opentelemetry-operator.v${OPENTELEMETRY_OPERATOR_RH_VERSION}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: rhobs-jaeger
    namespace: openshift-operators
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: jaeger-product
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: jaeger-operator.v${JAEGER_OPERATOR_RH_VERSION}
parameters:
- name: NAMESPACE
  value: observatorium-traces
- name: OPENTELEMETRY_OPERATOR_RH_VERSION
  value: 0.44.1-2
- name: JAEGER_OPERATOR_RH_VERSION
  value: 1.30.2
